#---------------------------
# Material-T
# 一款Material Design风格的HEXO主题
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: ../img/favicon.png
apple_touch_icon: ../img/apple-icon.png


#---------------------------
# 首页
# Index Page
#---------------------------
subtitle:
  enable: true

index_head_img: https://i.loli.net/2018/10/13/5bc1af44bb064.jpg 

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
menu:
  enable: true
  list:
    archives: /archives/
    about: /about/
  

social_icons:
  enable: true
  tips: 'See me here'
  list: 
    github: https://github.com/Luluno01/
    twitter: https://twitter.com/TE4mVEYvATuPC0p/
  

#---------------------------
# 文章页
# Post Page
#---------------------------
comments_type: 'disqus'
disqus: 
  shortname:

toc: 
  enable: true

# Code Highlight
# Theme available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
highlight:
  enable: true
  theme: tomorrow-night-eighties

  
#---------------------------
# 归档页
# Archive Page
#---------------------------
archive_head_img: ../img/post-head.jpg


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  head_img: https://i.loli.net/2018/10/18/5bc8833e75953.jpg
  avatar: ../img/avatar.png # https://i.loli.net/2018/10/12/5bc074d44218b.jpg 
  name: Untitled
  job:  student
  introduce: 强迫症患者/完美主义者
  extension: 关键词：折腾，计算机科学，音乐

about_icons:
  github: https://github.com/Luluno01/
  twitter: https://twitter.com/TE4mVEYvATuPC0p/


#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <b>someone.drink(new HotWater)</b>
